apiVersion: v1
kind: Service
metadata:
  name: auth-client
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  auth_client_mapping
      prefix: /auth/
      service: auth-client:8080
      bypass_auth: true
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
  selector:
    app: auth-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-client
spec:
  selector:
    matchLabels:
      app: auth-client
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: auth-client
        version: '10'
    spec:
      containers:
      - name: auth-client
        image: jasonblanchard/jawn-auth-client:10
        env:
          - name: 'PORT'
            value: '8080'
          - name: 'HOMEPAGE_PATH'
            value: '/workspace'
          - name: 'AUTH_API_PATH'
            value: '/auth/api/login'
          - name: 'BASE_PATH'
            value: '/auth'
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
             path: /health
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
