apiVersion: v1
kind: Service
metadata:
  name: auth-api
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: AuthService
      name: authentication
      auth_service: "auth-api:8080"
      path_prefix:  "/session/authn"
      proto: http
      allow_request_body: true
      allowed_request_headers:
        - "CSRF-Token"
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  auth_mapping
      prefix: /auth/api/
      service: auth-api:8080
      bypass_auth: true
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
  selector:
    app: auth-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  selector:
    matchLabels:
      app: auth-api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: auth-api
        version: '7'
    spec:
      containers:
      - name: auth-api
        image: jasonblanchard/jawn-auth:7
        env:
          - name: 'PORT'
            value: '8080'
          - name: 'LOGIN_PATH'
            value: '/auth/login'
          - name: 'JWT_SECRET'
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: jwtSecret
          - name: 'SESSION_SECRET'
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: sessionSecret
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
             path: /health
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
