apiVersion: v1
kind: Service
metadata:
  name: auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  auth_mapping
      prefix: /auth/api/
      service: auth:8080
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
  selector:
    app: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: auth
        version: '3'
    spec:
      containers:
      - name: auth
        image: jasonblanchard/jawn-auth:3
        env:
          - name: 'PORT'
            value: '8080'
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
             path: /health
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
