language: node_js
env:
  - DOCKER_COMPOSE_VERSION=1.23.1
before_install:
  # Install latest Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Install latest docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
services:
  - docker
script:
  - docker-compose -f docker-compose.ci.yml build
  - docker-compose -f docker-compose.ci.yml up -d
  - sleep 15 # TODO: Loop and check health of container
  - docker ps -a
  - docker-compose -f docker-compose.ci.yml exec -T app bash -c "cd /home/app/webapp/client && npm run test"
  - docker-compose -f docker-compose.ci.yml run tests bash -c "cd /home/app/tests && npm run cypress:run"
after_failure:
  - docker-compose -f docker-compose.ci.yml logs
