language: node_js
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.1
    - secure: GMWGNu0igi/Wq6V6L5iU7AwTw9eJbXVmSscPFzP+6xf/MNfc7bpmG7/+p0lISXTrwYf7yPvYfsMA7y34slp5aqkmCt4Y+INcmO2JM/MmywhdHWtwGv1b5QW2gjWA7H46IIxrADhiDPeUh7pdoHGd0iWHqZ7guc56tEui98PGw0AqlDVQD4PUJSLZwRXiJ9SJBYXKugRt3jZpgEsazL4wa1oM8chob2E72KWkVj4C3KXBMRX2sdF3mrIK1K8mvCx2Zr9WeyisjvfV7K6e3ybU7BjdPNS2ox+ov58CoGAgIwKwk3RuloShFjIlhY6M6AYHN1wCPbovCGi7hIqpPGLZdmZMeoETC8Hbxf8llXxprq/IJi2QAgQUlIhggeOyAvk9BdEEl09cno6XQPMi0qwFtMaBgk7uPdzg8s12UNQDopZhuY7h5r22omi2C80n2hM74tfhUmZ84MReqIhxd8tLZtgY3W5xcz0HWiUGGppQ/0x2o6nGJXi7YVkWufczonNobfUZllhw1iMzrDKwFxAU/Jpr2yMkvW1WjsqYJ+Ijz5uRuEqs1gsazzL4XWbOXuJ+5z8hZwSAq5Mg6EhUzC98+ZaDxlsx9H4Psbb2TgD6Utqti8WgHT55fJtquK386pCrbnsAac/+V4zVbkT2fb2MHlRWyRDDeIxVYyB2E597Aw0=
    - secure: NDp2/XKhh717V95YtfulWP0N8K2HxrPdl6Hs3zOgIknjb/sQjZ93Ea32bIeT5dNTCI314T6DVIRRR33UNPulWL5adpkhJs4kmq7xshIHuELbwl/oqpxh4Z3cO5+s+m3s/pfL4y04i/1NFpBDdBxq/BWcNyv3oY/z/cR/57YJpfBVtKapu9WqDloP/Qm7MdawUxmbLxey4qbwhYR0gZ9YQdjrKYJ5T539zlsYOHny3hVK+N5JwlU5bxkw1YBzsCb0ja+7QvL07///hmcd0PdmVxFn9Bogimnjd/kiLaCRpD4dF+kup4Iee50iIrYlCnVnAeHgTINmPxdQPubjeYw5jjM66GqHRvra8ZfHWd+etBZjgb0aLyXBi4qM/ZQffj6s0p9NF4P+UDkMQ1PsDA2Gmd7PAaBRZiLY+LXaboVeTVLUFr+TjPGKZKBBbJ236LYk79TCN7q8b050byOT6MoBosORugQAvhT6XdJ5JrE0eUuVOKrcg50xodiIXPyRPn+3dG31bGD6tQpfhI+tWKuNiC9USV8OkKzQu2AwOnWBW4OMKR68kjNk4c6N0g4eF4g4sYZnc+epTXGHyf0yrmNz0ht08PvRYiJK6QiHhzMgnpw+Bt7vryRkc67JR1nEE67mcuOi/6+wwPSK9zFK/XHCAABlxODmpWC9+kuExyR0oxo=
before_install:
  # Install latest Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Install latest docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
services:
  - docker
script:
  - docker-compose -f docker-compose.ci.yml build
  - docker-compose -f docker-compose.ci.yml up -d
  - sleep 15 # TODO: Loop and check health of container
  - docker ps -a
  - docker-compose -f docker-compose.ci.yml exec -T app bash -c "cd /home/app/webapp/client && npm run test"
  - docker-compose -f docker-compose.ci.yml run tests bash -c "cd /home/app/tests && npm run cypress:run"
deploy:
  provider: script
  script: bash ./scripts/docker_push
  on:
    branch: master
after_failure:
  - docker-compose -f docker-compose.ci.yml logs
