language: node_js
services:
  - docker
before_install:
  - docker-compose -f docker-compose.ci.yml build
  - docker-compose -f docker-compose.ci.yml up -d
script:
  - docker-compose -f docker-compose.ci.yml run tests bash -c "cd /home/app/tests && npm run cypress:run"
  - docker-compose -f docker-compose.ci.yml exec -T app bash -c "cd /home/app/webapp/client && npm run test"
after_failure:
  - docker-compose -f docker-compose.ci.yml logs
