language: node_js
env:
  - DOCKER_COMPOSE_VERSION=1.23.1
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
services:
  - docker
script:
  - docker-compose -f docker-compose.ci.yml build
  - docker-compose -f docker-compose.ci.yml up -d
  - sleep 30 # TODO: Loop and check health of container
  - docker ps -a
  # - docker-compose -f docker-compose.ci.yml exec -T app bash -c "cd /home/app/webapp/client && npm run test"
  - docker-compose -f docker-compose.ci.yml run tests bash -c "cd /home/app/tests && npm run cypress:run"
after_failure:
  - docker-compose -f docker-compose.ci.yml logs
