version: "3"
services:
  app:
    build: .
    image: jasonblanchard/jawn-app
    expose:
      - '80'
    networks:
      - backend
    environment:
      DB_NAME: jawn_test
      MONGO_HOST: mongo
      PORT: '8081'
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"] # TODO: Create a real health check endpoint
      interval: 15s
      timeout: 10s
      retries: 3
      # start_period: 40s
  mongo:
    image: mongo:3.7.1
    networks:
      - backend
  tests:
    build: ./tests
    environment:
      CYPRESS_BASE_URL: http://app
      MONGO_HOST: mongo
      DB_NAME: jawn_test
    networks:
      - backend
    volumes:
      - ./tests/cypress/videos:/home/app/tests/cypress/videos
      - ./tests/cypress/screenshots:/home/app/tests/cypress/screenshots
    depends_on:
      - mongo
      - app
    # command: bash -c "cd /home/app/tests && npm run cypress:run"
networks:
  backend:
