version: "3"
services:
  app:
    build: .
    image: jasonblanchard/jawn-app
    ports:
        - "80:80"
    networks:
      - frontend
      - backend
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
    deploy:
      replicas: 1
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
        - "dbdata:/data/db"
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  frontend:
  backend:
volumes:
  dbdata:
