apiVersion: v1
kind: Service
metadata:
  name: workspace
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  workspace_mapping
      prefix: /workspace/
      service: workspace
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  workspace_static_mapping
      prefix: /static/
      rewrite: ""
      service: workspace
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: workspace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace
spec:
  selector:
    matchLabels:
      app: workspace
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: workspace
        version: '1'
    spec:
      containers:
      - name: workspace
        image: jasonblanchard/jawn-workspace
        env:
          - name: 'PORT'
            value: '80'
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
             path: /health
             port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
