apiVersion: v1
kind: Service
metadata:
  name: workspace
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  workspace_mapping
      prefix: /
      service: workspace
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: workspace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace
spec:
  selector:
    matchLabels:
      app: workspace
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: workspace
        version: '4'
    spec:
      containers:
      - name: workspace
        image: jasonblanchard/jawn-workspace:4
        env:
          - name: 'PORT'
            value: '80'
          - name: 'MONGO_HOST'
            value: 'mongo'
          - name: 'DB_NAME'
            value: 'jawn'
          - name: 'LOG_LEVEL'
            value: 'DEBUG'
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
             path: /health
             port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
